# Generated by Django 3.2.7 on 2021-09-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessionscore',
            name='score',
            field=models.IntegerField(),
        ),
    ]
